### ISSUE TITLE
Idea: "squared.js"

### ISSUE THREAD

**Issue by mattdesl** [zeke/euclidean-distance#3]
Often in graphics dev you only need the squared result and can avoid a `sqrt` operation. It might be cool to expose the following:

``` js
var distSq = require('euclidean-distance/squared')
```

It would also go well alongside this module:
https://github.com/mattdesl/magnitude

**Comment by zeke** [comment]
Hi @mattdesl. Six months later, your wish is granted! For some reason I wasn't subscribed to github notifications for this repo, so I missed this issue. I just published 1.0.0 with the above-suggested `squared` support.
