### ISSUE TITLE
Please provide a license file

### ISSUE THREAD

**Issue by williamjmorenor** [zeke/euclidean-distance#4]
Hi

I am packaging this app in Fedora:
https://bugzilla.redhat.com/show_bug.cgi?id=1275008

Please include the license text to include it in the RPM

**Comment by zeke** [comment]
Hi @williamjmorenor, glad you're finding a use for this module. I just added an MIT license, included in v0.3.0

What are you using it for, out of curiosity?

**Comment by williamjmorenor** [comment]
Thanks

I am packging i3style than requires color-namer than requires euclidean-distance. 

By the way i have requested the review of color-namer to, so maybe you can include the license text for color-namer :)

https://bugzilla.redhat.com/show_bug.cgi?id=1274930

Regards

**Comment by zeke** [comment]
This color-namer? https://github.com/zeke/color-namer

I don't see an issue.
